name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install QEMU for cross compilation
        id: QEMU
        uses: docker/setup-qemu-action@v1


