name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install QEMU for cross compilation
        id: QEMU
        uses: docker/setup-qemu-action@v1
      - run: ./docker_build.sh build "arm32v7/node:10-buster"
      - run: ./docker_build.sh build "arm32v7/node:12-buster"
      - run: ./docker_build.sh build "arm32v6/node:erbium-alpine"
      - run: ./docker_build.sh build "arm32v7/node:14-buster"
      - run: ./docker_build.sh build "arm64v8/node:12-buster"
      




